include:
  - local: '/default_variables.yml'

stages:
  - deploy

deploy_job:
  stage: deploy
  image: $DEPLOY_IMAGE
  script:
    - echo "Running deploy pipeline"
    - echo "Put your deploy commands here"
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never